name: immunityunity

on:
  schedule:
    - cron: '1 22 * * *'

jobs:
  run-immunityunity:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.3'
          
      - name: Install rtweet package
        run: Rscript -e 'install.packages(c("rtweet", "dplyr", "ggplot2"), dependencies = TRUE)'
        
      - name: Download Parse and Tweet
        run: Rscript vax.R
        
      # Add new files in data folder, commit along with other modified files, push
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
